spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    #        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    ROOT: info
    org.hibernate.SQL: debug
#  org.hibernate.type: trace
