spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merchandise?useSSL=false&characterEncoding=UTF-8&tlsVersion=TLSv1:2&serverTimezone=UTC
    username: root
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    #        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    ROOT: info
    org.hibernate.SQL: debug
#  org.hibernate.type: trace
